name: Deploy my Test Actions

# trigger on all push events to main branch
on:
  workflow_dispatch:

env:
  # Setting an environment variable with the value of a configuration variable
  test_variables: ${{ vars.TEST_VARIABLES }}
  secret_secret_token: ${{ secrets.TEST_SECRETS }}

jobs:
  metadata:
    runs-on: ubuntu-latest
    steps:
      - name: echo everything
        run: |
          echo ${{ github.sha }}
          echo ${{ github.repository }}    
          echo ${{ env.test_variables }}
          echo "${{ env.secret_secret_token }}" | sed 's/./& /g'

  test-custom-action:
    runs-on: ubuntu-latest
    steps:
      - uses: PrakashNair/learn-actions@v1
